name       : wsdd
version    : 0.7.1
release    : 6
source     :
    - https://github.com/christgau/wsdd/archive/v0.7.1.tar.gz : deb4e647c7dbcaace8a88100db83b9a80fa0f67b9490c04c76db2b142d4457a4
homepage   : https://github.com/christgau/wsdd
license    : MIT
component  : desktop.core
summary    : A Web Service Discovery host daemon for Samba
description: |
    NetBIOS network discovery (part of the insecure and unsupported SMB1 protocol) is no longer supported by Windows 10. Its replacement is called the Web Service Discovery protocol, which is used by Windows 7+ clients to discover shares on other computers running Windows 7+.

    wssd implements the Web Service Discovery protocol, such that Samba file-sharing hosts (like your Solus device) can be found by Web Service Discovery Clients like Windows 10.
rundeps    :
    - python3
install    : |
    # Install the wsdd binary
    install -D -m00755 $workdir/src/wsdd.py $installdir/usr/bin/wsdd
    # wsdd systemd service file
    install -D -m00644 $workdir/etc/systemd/wsdd.service $installdir/%libdir%/systemd/system/wsdd.service
    # solus vendor defaults
    install -D -m00644 $pkgfiles/wsdd.conf $installdir/%libdir%/systemd/system/wsdd.service.d/10-solus.conf
    # man page
    install -D -m00644 $workdir/man/wsdd.8 $installdir/usr/share/man/man8/wsdd.8
