name       : wsdd
version    : 0.6.4
release    : 2
source     :
    - https://github.com/christgau/wsdd/archive/v0.6.4.tar.gz : bb8bc6411b70be68369c53bf75827ac77f16a5bf5606de6536dd7e6d6ce4c2be
license    : MIT
component  : desktop.core
summary    : A Web Service Discovery host daemon for Samba
description: |
    NetBIOS network discovery (part of the insecure and unsupported SMB1 protocol) is no longer supported by Windows 10. Its replacement is called the Web Service Discovery protocol, which is used by Windows 7+ clients to discover shares on other computers running Windows 7+.

    wssd implements the Web Service Discovery protocol, such that Samba file-sharing hosts (like your Solus device) can be found by Web Service Discovery Clients like Windows 10.
rundeps    :
    - python3
setup      : |
    %patch -p1 < $pkgfiles/wsdd-systemd-service.patch
install    : |
    # Install the wsdd binary
    install -d -m00755 $installdir/usr/bin
    install -D -m00755 $workdir/src/wsdd.py $installdir/usr/bin/wsdd
    # wsdd user+group configuration
    install -d -m00755 $installdir/%libdir%/sysusers.d
    install -D -m00644 $pkgfiles/wsdd.sysusers $installdir/%libdir%/sysusers.d/wsdd.conf
    # create /run/wsdd/chroot on boot
    install -D -m00644 $pkgfiles/wsdd.tmpfiles $installdir/%libdir%/tmpfiles.d/wsdd.conf
    # wsdd systemd service file
    install -d -m00755 $installdir/%libdir%/systemd/system
    install -D -m00644 $workdir/etc/systemd/wsdd.service $installdir/%libdir%/systemd/system/wsdd.service
    # man page
    install -d -m00755 $installdir/usr/share/man/man1
    install -D -m00644 $workdir/man/wsdd.1 $installdir/usr/share/man/man1/wsdd.1

